Feature/menu hamburguer
marceloglacial/2020-brinca pull request #81
Opened 2022-07-29 12:22 UTC by dutraneto

2022-07-29 13:12 UTC, marceloglacial requested changes
![Screen Shot 2022-07-29 at 9 00 53 AM](https://user-images.githubusercontent.com/11657599/181767821-28665662-d1e6-486b-b2a1-4e4c57527456.png)
![Screen Shot 2022-07-29 at 9 01 13 AM](https://user-images.githubusercontent.com/11657599/181767824-38e1edc8-3e16-44e2-a428-a9bef8a07d7c.png)
![Screen Shot 2022-07-29 at 9 01 20 AM](https://user-images.githubusercontent.com/11657599/181767827-6e8fa76c-f7ca-42c2-8ff6-5f9584e680f7.png)
![Screen Shot 2022-07-29 at 9 10 16 AM](https://user-images.githubusercontent.com/11657599/181767829-9ac1b064-e468-49a9-845f-d4be9f30296f.png)

2022-08-03 12:03 UTC, marceloglacial requested changes
![Screen Shot 2022-08-03 at 8 00 15 AM](https://user-images.githubusercontent.com/11657599/182603178-f917c7d1-a776-4afd-924a-f60c8b4f5c18.png)
![Screen Shot 2022-08-03 at 8 00 09 AM](https://user-images.githubusercontent.com/11657599/182603179-006aa32e-6fb5-4f66-8787-a091ed739eff.png)

2022-08-04 02:10 UTC, dutraneto commented
> ![Screen Shot 2022-08-03 at 8 00 15 AM](https://user-images.githubusercontent.com/11657599/182603178-f917c7d1-a776-4afd-924a-f60c8b4f5c18.png) ![Screen Shot 2022-08-03 at 8 00 09 AM](https://user-images.githubusercontent.com/11657599/182603179-006aa32e-6fb5-4f66-8787-a091ed739eff.png)

I have made the button smaller, mad space even to the borders as much as possibe (padding top is 15px and right/left 12px). Close button space even to the borders

2022-08-04 12:50 UTC, marceloglacial approved these changes

2022-08-04 14:48 UTC, merged